# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Davinci_Project/pcie_test_4/pcie_test_4.cache/wt [current_project]
set_property parent.project_path D:/Davinci_Project/pcie_test_4/pcie_test_4.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Davinci_Project/pcie_test_4/pcie_test_4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/new/gmii_2_rgmii.v
  D:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/new/gmii_to_rgmii.v
  D:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/new/rgmii_rx1.v
  D:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/new/rgmii_rx2.v
  D:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/new/rgmii_tx1.v
  D:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/new/rgmii_tx2.v
  D:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/new/udp_rx.v
  D:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/new/udp_top.v
  D:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
}
add_files D:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_4/pcie2_fifo_generator_tgt_brdg.xdc]
set_property used_in_implementation false [get_files -all d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_3/pcie2_fifo_generator_dma_cpl.xdc]
set_property used_in_implementation false [get_files -all d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_2/xdma_v4_1_4_blk_mem_64_noreg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_1/xdma_v4_1_4_blk_mem_64_reg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie2_ip-PCIE_X0Y0.xdc]
set_property used_in_implementation false [get_files -all d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/synth/design_1_xdma_0_0_pcie2_ip_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/design_1_xdma_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/source/design_1_xdma_0_0_pcie3_7vx_ip.xdc]
set_property used_in_implementation false [get_files -all d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/synth/design_1_xdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0/design_1_util_ds_buf_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0/design_1_util_ds_buf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_0/design_1_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_1/design_1_axis_data_fifo_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

read_ip -quiet d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc]

read_ip -quiet d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
set_property used_in_implementation false [get_files -all d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc]
set_property used_in_implementation false [get_files -all d:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/constrs_1/new/pins.xdc
set_property used_in_implementation false [get_files D:/Davinci_Project/pcie_test_4/pcie_test_4.srcs/constrs_1/new/pins.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_1_wrapper -part xc7a100tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
