@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Sun Nov 07 14:56:12 +0800 2021
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto f7ba9aed2382417f8d362ba2710e6b93 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L blk_mem_gen_v8_4_4 -L fifo_generator_v13_1_4 -L xdma_v4_1_4 -L axi_lite_ipif_v3_0_4 -L lib_cdc_v1_0_2 -L interrupt_control_v3_1_4 -L axi_gpio_v2_0_22 -L fifo_generator_v13_2_5 -L axis_infrastructure_v1_1_0 -L axis_data_fifo_v2_0_2 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot udp_top_tb_behav xil_defaultlib.udp_top_tb xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto f7ba9aed2382417f8d362ba2710e6b93 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L blk_mem_gen_v8_4_4 -L fifo_generator_v13_1_4 -L xdma_v4_1_4 -L axi_lite_ipif_v3_0_4 -L lib_cdc_v1_0_2 -L interrupt_control_v3_1_4 -L axi_gpio_v2_0_22 -L fifo_generator_v13_2_5 -L axis_infrastructure_v1_1_0 -L axis_data_fifo_v2_0_2 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot udp_top_tb_behav xil_defaultlib.udp_top_tb xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
