webtalk_init -webtalk_dir E:/FPGA/pcie_test_4/pcie_test_4/pcie_test_4.sim/sim_1/behav/xsim/xsim.dir/udp_top_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Nov  7 15:11:48 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0f8fee6f-7701-4920-bba9-a8692f7a612e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f7ba9aed2382417f8d362ba2710e6b93" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "101" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.15_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15044_KB" -context "xsim\\usage"
webtalk_transmit -clientid 154074347 -regid "" -xml E:/FPGA/pcie_test_4/pcie_test_4/pcie_test_4.sim/sim_1/behav/xsim/xsim.dir/udp_top_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/FPGA/pcie_test_4/pcie_test_4/pcie_test_4.sim/sim_1/behav/xsim/xsim.dir/udp_top_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/FPGA/pcie_test_4/pcie_test_4/pcie_test_4.sim/sim_1/behav/xsim/xsim.dir/udp_top_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
